# Generated by Django 5.2.6 on 2025-10-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='description',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
